spring:
  application:
    name: config_server
    retry:
      enabled: true
    cloud:
        config:
            server:
                git:
                    timeout: 5000
            fail-fast: true
# we could have diff git repo url for config repo for each env if needed
#            git:
#                uri:https://github.com/shivamlc/ai-news-platform-config-prod.git               

management:
  endpoints:
    web:
      exposure:
        include: "health,info" # This exposes only the following Spring Boot Actuator endpoints over HTTP -> /actuator/health, /actuator/info.


logging:
  level:
    root: INFO