spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:}
    password: ${SPRING_RABBITMQ_PASSWORD:}

encrypt:
  key: ${CONFIG_ENCRYPTION_KEY:} # Use the ENCRYPTION_KEY environment variable or default if not set
