spring:
  application:
    name: config_server (dev)

management:
  endpoints:
    web:
      exposure:
        include: "health,info,busrefresh" # This exposes only the following Spring Boot Actuator endpoints over HTTP -> /actuator/health, /actuator/info, /actuator/busrefresh.

encrypt:
    key: ${CONFIG_ENCRYPTION_KEY:} # Use the ENCRYPTION_KEY environment variable or default if not set

rabbitmq:
    host: ${RABBIT_MQ_HOST:}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:}
    password: ${RABBIT_MQ_PASSWORD:}